export const BADGE_DEFS = [
  { id: 'eeg', title: 'EEG', image: '/images/eeg.jpg' },
  { id: 'eeg2', title: 'EEG2', image: '/images/eeg2.webp' },
  { id: 'experiment', title: 'Experiment', image: '/images/experiment.webp' },
  { id: 'facereader', title: 'Facereader', image: '/images/facereader.webp' },
  { id: 'excursie', title: 'Excursie', image: '/images/excursie.webp' },
  { id: 'groupname', title: 'Groepsnaam & mascotte', image: '/images/groupname.webp' },
  { id: 'homework', title: 'Homework', image: '/images/homework.webp' },
  { id: 'kennistoets', title: 'Kennistoets', image: '/images/kennistoets.webp' },
  { id: 'leeswerk', title: 'Leeswerk', image: '/images/leeswerk.webp' },
  { id: 'lunch', title: 'Lunch', image: '/images/lunch.webp' },
  { id: 'meeting', title: 'Meeting with commissioner', image: '/images/meeting.webp' },
  { id: 'minorbehaald', title: 'Minor behaald', image: '/images/minorbehaald.webp' },
  { id: 'namen', title: 'Namen badge', image: '/images/namen-badge.webp' },
  { id: 'partycommittee', title: 'Party committee', image: '/images/partycommittee.webp' },
  { id: 'project', title: 'Project', image: '/images/project.webp' },
  { id: 'pubquiz', title: 'Pubquiz', image: '/images/pubquiz.webp' },
  { id: 'pupil-labs', title: 'Pupil labs', image: '/images/pupil-labs.webp' },
];
